services:
  app:
    image: mcr.microsoft.com/devcontainers/universal:2-focal
    command: sleep infinity
    volumes:
      - ..:/workspace:cached

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: LocalPasswordOnly

volumes:
  postgres-data:
