services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    command: sleep infinity
    volumes:
      - ../..:/workspaces:cached

  postgres:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      PGPORT: 5433
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: LocalPasswordOnly

volumes:
  postgres-data:
