name: Run Tests
on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: test
    container: mcr.microsoft.com/playwright:v1.47.2-noble
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: tmshkr/ngrok-ssh@latest
        with:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
          WAIT_FOR_CONNECTION: true
      - run: npm ci
      - run: npm run test --workspace functions
        env:
          TEST_DATABASE_URL: ${{ vars.TEST_DATABASE_URL }}
